### ISSUE TITLE
Passiert hier noch etwas?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/articlelist#1]

**Comment by skerbis** [comment]
@schuer ping!

**Comment by schuer** [comment]
Huch, ich. Warum? Ich habe nichts mit dem AddOn zu tun :)

**Comment by skerbis** [comment]
@schuer sehe hier nur eine Person: https://github.com/FriendsOfREDAXO/articlelist/graphs/contributors

**Comment by schuer** [comment]
Oh okay, ich hatte die License eingefügt und die README ergänzt. Angelegt hat das Projekt aber @tgoellner, siehe https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/blob/e90c59fab02a97c335152dff38a22c1b651a6653/_data/projects.yml#L6 und https://friendsofredaxo.github.io

**Comment by skerbis** [comment]
Da hier seit 8 Monaten nichts lief, kann es eigentlich wohl weg - oder?

**Comment by schuer** [comment]
Es ist ja als Idee »reserviert«, so wie andere Projekte bei FOR (etwa: blog), deshalb würde ich es der Person überlassen, die es initiiert hat, zu entscheiden, was damit passiert.

**Comment by skerbis** [comment]
Aber genau das ist mehr oder minder das Problem, jemand macht "blog" und kein anderer traut sich mehr - wäre schade

**Comment by schuer** [comment]
Es fehlt leider oft an Kommunikation drumrum: Was ist das für ein Projekt? Warum will ich es machen? Wie soll es umgesetzt werden? Wer hat Lust, mitzumachen? Welche Features implementieren wir und in welcher Form? Wer übernimmt welche Aufgaben? Usw.

Das passiert bei FOR leider noch viel zu wenig, und deshalb entstehen Projekte wie dieses hier, von dem niemand weiß, was es ist und warum es angelegt wurde. Aber jemand von uns hatte ja mal eine Absicht damit, und ich denke nicht, dass es andere Leute davon abhält, ihre eigenen Ideen hier anzustoßen.

Deshalb würde ich es nicht einfach entfernen, nur weil es noch nicht _bespielt_ wurde.

**Comment by skerbis** [comment]
Gut dann: Was ist hier geplant, gibt es was wo man mithelfen kann? @tgoellner

**Comment by ghost** [comment]
?
